name: Deploy Laravel to InfinityFree
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Laravel to InfinityFree
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install PHP and Composer
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Install Composer Dependencies
      run: composer install --no-dev --optimize-autoloader

    - name: Build Assets (Optional)
      run: |
        npm install
        npm run prod

    - name: Prepare Laravel for Production
      run: |
        cp .env.example .env
        php artisan config:cache
        php artisan route:cache
        php artisan view:cache

    - name: Deploy to InfinityFree
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.HOSTNAME }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        local-dir: ./  
        server-dir: /htdocs  
